// Generated by CoffeeScript 1.10.0
(function() {
  var CSON, Please, fs, namespace, path, postcss;

  fs = require('fs');

  path = require('path');

  CSON = require('cson');

  postcss = require('postcss');

  Please = require('pleasejs');

  namespace = postcss.plugin('postcss-namespace', function(opts) {
    if (opts == null) {
      opts = {
        token: '-'
      };
    }
    return function(css) {
      return css.replaceValues(/random\(([^\)]*)\)/, {
        fast: 'random'
      }, function(m, arg) {
        var result;
        return result = (function() {
          switch (arg) {
            case '':
              return Please.make_color()[0];
          }
        })();
      });
    };
  });

  module.exports = namespace;

}).call(this);
